export enum SurvivingMarsMapName {
  BlankBig_01 = 'BlankBig_01',
  BlankBig_02 = 'BlankBig_02',
  BlankBig_03 = 'BlankBig_03',
  BlankBig_04 = 'BlankBig_04',
  BlankBigCanyonCMix_01 = 'BlankBigCanyonCMix_01',
  BlankBigCanyonCMix_02 = 'BlankBigCanyonCMix_02',
  BlankBigCanyonCMix_03 = 'BlankBigCanyonCMix_03',
  BlankBigCanyonCMix_04 = 'BlankBigCanyonCMix_04',
  BlankBigCanyonCMix_05 = 'BlankBigCanyonCMix_05',
  BlankBigCanyonCMix_06 = 'BlankBigCanyonCMix_06',
  BlankBigCanyonCMix_07 = 'BlankBigCanyonCMix_07',
  BlankBigCanyonCMix_08 = 'BlankBigCanyonCMix_08',
  BlankBigCanyonCMix_09 = 'BlankBigCanyonCMix_09',
  BlankBigCanyonCMix_10 = 'BlankBigCanyonCMix_10',
  BlankBigCliffsCMix_01 = 'BlankBigCliffsCMix_01',
  BlankBigCliffsCMix_02 = 'BlankBigCliffsCMix_02',
  BlankBigCrater_01 = 'BlankBigCrater_01',
  BlankBigCraterCMix_01 = 'BlankBigCraterCMix_01',
  BlankBigCraterCMix_02 = 'BlankBigCraterCMix_02',
  BlankBigHeartCMix_03 = 'BlankBigHeartCMix_03',
  BlankBigTerraceCMix_01 = 'BlankBigTerraceCMix_01',
  BlankBigTerraceCMix_02 = 'BlankBigTerraceCMix_02',
  BlankBigTerraceCMix_03 = 'BlankBigTerraceCMix_03',
  BlankBigTerraceCMix_04 = 'BlankBigTerraceCMix_04',
  BlankBigTerraceCMix_05 = 'BlankBigTerraceCMix_05',
  BlankBigTerraceCMix_06 = 'BlankBigTerraceCMix_06',
  BlankBigTerraceCMix_07 = 'BlankBigTerraceCMix_07',
  BlankBigTerraceCMix_08 = 'BlankBigTerraceCMix_08',
  BlankBigTerraceCMix_09 = 'BlankBigTerraceCMix_09',
  BlankBigTerraceCMix_10 = 'BlankBigTerraceCMix_10',
  BlankBigTerraceCMix_11 = 'BlankBigTerraceCMix_11',
  BlankBigTerraceCMix_12 = 'BlankBigTerraceCMix_12',
  BlankBigTerraceCMix_13 = 'BlankBigTerraceCMix_13',
  BlankBigTerraceCMix_14 = 'BlankBigTerraceCMix_14',
  BlankBigTerraceCMix_15 = 'BlankBigTerraceCMix_15',
  BlankBigTerraceCMix_16 = 'BlankBigTerraceCMix_16',
  BlankBigTerraceCMix_17 = 'BlankBigTerraceCMix_17',
  BlankBigTerraceCMix_18 = 'BlankBigTerraceCMix_18',
  BlankBigTerraceCMix_19 = 'BlankBigTerraceCMix_19',
  BlankBigTerraceCMix_20 = 'BlankBigTerraceCMix_20',
  BlankTerraceBig_05 = 'BlankTerraceBig_05',
  /* ------ BELOW AND BEYOND DLC MAPS ------ */
  BlankUnderground_01 = 'BlankUnderground_01',
  BlankUnderground_02 = 'BlankUnderground_02',
  BlankUnderground_03 = 'BlankUnderground_03',
  BlankUnderground_04 = 'BlankUnderground_04',
}

export type SurvivingMarsMapId = keyof typeof SurvivingMarsMapName;


export const SurvivingMarsMapNameI18N = {
  [SurvivingMarsMapName.BlankBig_01]: 'Big 01',
  [SurvivingMarsMapName.BlankBig_02]: 'Big 02',
  [SurvivingMarsMapName.BlankBig_03]: 'Big 03',
  [SurvivingMarsMapName.BlankBig_04]: 'Big 04',
  [SurvivingMarsMapName.BlankBigCanyonCMix_01]: 'Big Canyon Mix 01',
  [SurvivingMarsMapName.BlankBigCanyonCMix_02]: 'Big Canyon Mix 02',
  [SurvivingMarsMapName.BlankBigCanyonCMix_03]: 'Big Canyon Mix 03',
  [SurvivingMarsMapName.BlankBigCanyonCMix_04]: 'Big Canyon Mix 04',
  [SurvivingMarsMapName.BlankBigCanyonCMix_05]: 'Big Canyon Mix 05',
  [SurvivingMarsMapName.BlankBigCanyonCMix_06]: 'Big Canyon Mix 06',
  [SurvivingMarsMapName.BlankBigCanyonCMix_07]: 'Big Canyon Mix 07',
  [SurvivingMarsMapName.BlankBigCanyonCMix_08]: 'Big Canyon Mix 08',
  [SurvivingMarsMapName.BlankBigCanyonCMix_09]: 'Big Canyon Mix 09',
  [SurvivingMarsMapName.BlankBigCanyonCMix_10]: 'Big Canyon Mix 10',
  [SurvivingMarsMapName.BlankBigCliffsCMix_01]: 'Big Cliffs Mix 01',
  [SurvivingMarsMapName.BlankBigCliffsCMix_02]: 'Big Cliffs Mix 02',
  [SurvivingMarsMapName.BlankBigCrater_01]: 'Big Crater 01',
  [SurvivingMarsMapName.BlankBigCraterCMix_01]: 'Big Crater Mix 01',
  [SurvivingMarsMapName.BlankBigCraterCMix_02]: 'Big Crater Mix 02',
  [SurvivingMarsMapName.BlankBigHeartCMix_03]: 'Big Hear Mix 03',
  [SurvivingMarsMapName.BlankBigTerraceCMix_01]: 'Big Terrace Mix 01',
  [SurvivingMarsMapName.BlankBigTerraceCMix_02]: 'Big Terrace Mix 02',
  [SurvivingMarsMapName.BlankBigTerraceCMix_03]: 'Big Terrace Mix 03',
  [SurvivingMarsMapName.BlankBigTerraceCMix_04]: 'Big Terrace Mix 04',
  [SurvivingMarsMapName.BlankBigTerraceCMix_05]: 'Big Terrace Mix 05',
  [SurvivingMarsMapName.BlankBigTerraceCMix_06]: 'Big Terrace Mix 06',
  [SurvivingMarsMapName.BlankBigTerraceCMix_07]: 'Big Terrace Mix 07',
  [SurvivingMarsMapName.BlankBigTerraceCMix_08]: 'Big Terrace Mix 08',
  [SurvivingMarsMapName.BlankBigTerraceCMix_09]: 'Big Terrace Mix 09',
  [SurvivingMarsMapName.BlankBigTerraceCMix_10]: 'Big Terrace Mix 10',
  [SurvivingMarsMapName.BlankBigTerraceCMix_11]: 'Big Terrace Mix 11',
  [SurvivingMarsMapName.BlankBigTerraceCMix_12]: 'Big Terrace Mix 12',
  [SurvivingMarsMapName.BlankBigTerraceCMix_13]: 'Big Terrace Mix 13',
  [SurvivingMarsMapName.BlankBigTerraceCMix_14]: 'Big Terrace Mix 14',
  [SurvivingMarsMapName.BlankBigTerraceCMix_15]: 'Big Terrace Mix 15',
  [SurvivingMarsMapName.BlankBigTerraceCMix_16]: 'Big Terrace Mix 16',
  [SurvivingMarsMapName.BlankBigTerraceCMix_17]: 'Big Terrace Mix 17',
  [SurvivingMarsMapName.BlankBigTerraceCMix_18]: 'Big Terrace Mix 18',
  [SurvivingMarsMapName.BlankBigTerraceCMix_19]: 'Big Terrace Mix 19',
  [SurvivingMarsMapName.BlankBigTerraceCMix_20]: 'Big Terrace Mix 20',
  [SurvivingMarsMapName.BlankTerraceBig_05]: 'Big Terrace 05',
  [SurvivingMarsMapName.BlankUnderground_01]: 'Underground 01',
  [SurvivingMarsMapName.BlankUnderground_02]: 'Underground 02',
  [SurvivingMarsMapName.BlankUnderground_03]: 'Underground 03',
  [SurvivingMarsMapName.BlankUnderground_04]: 'Underground 04',
} as const;
